DROP FUNCTION apply_effect;
DROP FUNCTION remove_effect;
DROP FUNCTION do_trade;
DROP FUNCTION demon_test;
DROP FUNCTION count_residents;
DROP FUNCTION mage_in_train_func;
DROP FUNCTION human_dead;


DROP TABLE MAGE CASCADE;
DROP TABLE SMOKE CASCADE;
DROP TABLE LOCATION CASCADE;
DROP TABLE DRUG CASCADE;
DROP TABLE ORGANIZATION;
DROP TABLE HUMAN CASCADE;
DROP TABLE DEVIL CASCADE;
DROP TABLE TEST;
DROP TABLE TRADE;
DROP TABLE TRAINING;