CREATE TABLE s265092.LOCATION( 
LOCALE_ID SMALLSERIAL PRIMARY KEY, 
LOC_NAME VARCHAR(25) NOT NULL, 
POPULATION INTEGER CHECK(POPULATION >= 0) NOT NULL 
);

CREATE TABLE s265092.DRUG( 
DRUG_ID SMALLSERIAL PRIMARY KEY, 
NAME VARCHAR(25) NOT NULL, 
DESCRIPTION TEXT,
POWER_MULT REAL DEFAULT 1,
SIDE_EFFECT_CHANCE DECIMAL DEFAULT 0.5,
COST INTEGER CHECK(COST >= 0) NOT NULL 
);

CREATE TABLE s265092.SMOKE( 
SMOKE_ID SMALLSERIAL PRIMARY KEY, 
ABILITY VARCHAR(25) NOT NULL, 
DESCRIPTION TEXT,
COST INTEGER CHECK(COST >= 0) NOT NULL 
);

CREATE TABLE s265092.ORGANIZATION( 
ORG_ID SMALLSERIAL PRIMARY KEY, 
HEAD_ID INTEGER NOT NULL,
NAME VARCHAR(20) NOT NULL, 
DESCRIPTION TEXT
);

CREATE TABLE s265092.MAGE( 
MAGE_ID SERIAL PRIMARY KEY, 
SMOKE_ID SMALLINT NOT NULL REFERENCES s265092.SMOKE(SMOKE_ID) ON DELETE CASCADE ON UPDATE CASCADE ,
LOCALE_ID SMALLINT NOT NULL REFERENCES s265092.LOCATION(LOCALE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
ORG_ID SMALLINT REFERENCES s265092.ORGANIZATION(ORG_ID) ON UPDATE CASCADE,
NAME VARCHAR(20) NOT NULL, 
MASK TEXT,
IN_TEST BOOLEAN DEFAULT false,
POWER_LVL SMALLINT CHECK(POWER_LVL >= 0 AND POWER_LVL <= 100) NOT NULL DEFAULT 20,
SIDE_EFFECT_CHANCE DECIMAL NOT NULL DEFAULT 0,
ALIVE BOOLEAN DEFAULT true,
MONEY INTEGER CHECK (MONEY >= 0) NOT NULL DEFAULT 0 
);

CREATE TABLE s265092.TRADE( 
TRADE_ID SERIAL PRIMARY KEY, 
SELLER_ID INTEGER NOT NULL REFERENCES s265092.MAGE(MAGE_ID) ON UPDATE CASCADE ON DELETE CASCADE,
BUYER_ID INTEGER NOT NULL REFERENCES s265092.MAGE(MAGE_ID) ON UPDATE CASCADE ON DELETE CASCADE,
SMOKE_ID SMALLINT REFERENCES s265092.SMOKE(SMOKE_ID),
DRUG_ID SMALLINT REFERENCES s265092.DRUG(DRUG_ID),
PRICE INTEGER CHECK(PRICE >= 0) DEFAULT 0 
);

CREATE TABLE s265092.TRADE_INST( 
PARTICIPANT_ID INTEGER NOT NULL REFERENCES s265092.MAGE(MAGE_ID) ON UPDATE CASCADE ON DELETE CASCADE,
TRADE_ID INTEGER NOT NULL REFERENCES s265092.TRADE(TRADE_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE s265092.DEVIL( 
DEVIL_ID SMALLSERIAL PRIMARY KEY,
PREV_MAGE INTEGER REFERENCES s265092.MAGE(MAGE_ID) ON UPDATE CASCADE,
NAME VARCHAR(25) NOT NULL
);

CREATE TABLE s265092.TEST( 
MAGE_ID INTEGER REFERENCES s265092.MAGE(MAGE_ID) PRIMARY KEY,
DEVIL_ID SMALLINT REFERENCES s265092.DEVIL(DEVIL_ID),
RESULT TEXT DEFAULT 'Had not passed.'
);

CREATE TABLE s265092.HUMAN( 
PERSON_ID SERIAL PRIMARY KEY,
EFFECT_FROM INTEGER REFERENCES s265092.MAGE(MAGE_ID) ON UPDATE CASCADE,
NAME VARCHAR(25) NOT NULL,
EFFECT text,
ALIVE BOOLEAN DEFAULT true
);

CREATE TABLE s265092.TRAINING( 
TRAIN_ID SERIAL PRIMARY KEY, 
LEAD_MAGE INTEGER NOT NULL REFERENCES s265092.MAGE(MAGE_ID) ON UPDATE CASCADE ON DELETE CASCADE,
SIDEKICK INTEGER REFERENCES s265092.MAGE(MAGE_ID) ON UPDATE CASCADE ON DELETE CASCADE,
VICTIM INTEGER REFERENCES s265092.HUMAN(PERSON_ID) ON UPDATE CASCADE ON DELETE CASCADE,
RESULT TEXT
);

CREATE TABLE s265092.TRADE_INST( 
TRAINEE_ID INTEGER NOT NULL REFERENCES s265092.MAGE(MAGE_ID) ON UPDATE CASCADE ON DELETE CASCADE,
TRAIN_ID INTEGER NOT NULL REFERENCES s265092.TRAINING(TRADE_ID) ON UPDATE CASCADE ON DELETE CASCADE
);
