CREATE TABLE LOCATION( 
LOCALE_ID SMALLSERIAL PRIMARY KEY, 
LOC_NAME VARCHAR(25) NOT NULL, 
POPULATION INTEGER CHECK(POPULATION >= 0) NOT NULL 
);

CREATE TABLE DRUG( 
DRUG_ID SMALLSERIAL PRIMARY KEY, 
NAME VARCHAR(25) NOT NULL, 
DESCRIPTION TEXT,
POWER_MULT REAL DEFAULT 1,
SIDE_EFFECT_CHANCE DECIMAL DEFAULT 0.5,
COST INTEGER CHECK(COST >= 0) NOT NULL 
);

CREATE TABLE SMOKE( 
SMOKE_ID SMALLSERIAL PRIMARY KEY, 
ABILITY VARCHAR(25) NOT NULL, 
DESCRIPTION TEXT,
COST INTEGER CHECK(COST >= 0) NOT NULL 
);

CREATE TABLE ORGANIZATION( 
ORG_ID SMALLSERIAL PRIMARY KEY, 
HEAD_ID INTEGER NOT NULL,
NAME VARCHAR(20) NOT NULL, 
DESCRIPTION TEXT
);

CREATE TABLE MAGE( 
MAGE_ID SERIAL PRIMARY KEY, 
SMOKE_ID SMALLINT NOT NULL REFERENCES SMOKE(SMOKE_ID) ON DELETE CASCADE ON UPDATE CASCADE ,
LOCALE_ID SMALLINT NOT NULL REFERENCES LOCATION(LOCALE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
ORG_ID SMALLINT REFERENCES ORGANIZATION(ORG_ID) ON UPDATE CASCADE,
NAME VARCHAR(20) NOT NULL UNIQUE, 
MASK TEXT,
IN_TEST BOOLEAN DEFAULT false,
POWER_LVL SMALLINT CHECK(POWER_LVL >= 0 AND POWER_LVL <= 100) NOT NULL DEFAULT 20,
SIDE_EFFECT_CHANCE DECIMAL NOT NULL DEFAULT 0,
ALIVE BOOLEAN DEFAULT true,
MONEY INTEGER CHECK (MONEY >= 0) NOT NULL DEFAULT 0 
);

CREATE TABLE TRADE( 
TRADE_ID SERIAL PRIMARY KEY, 
SMOKE_ID SMALLINT REFERENCES SMOKE(SMOKE_ID) ON UPDATE CASCADE,
DRUG_ID SMALLINT REFERENCES DRUG(DRUG_ID) ON UPDATE CASCADE
);

CREATE TABLE TRADE_MAGE( 
SELLER_ID INTEGER NOT NULL REFERENCES MAGE(MAGE_ID) ON UPDATE CASCADE ON DELETE CASCADE PRIMARY KEY,
BUYER_ID INTEGER NOT NULL REFERENCES MAGE(MAGE_ID) ON UPDATE CASCADE ON DELETE CASCADE PRIMARY KEY,
TRADE_ID INTEGER NOT NULL REFERENCES TRADE(TRADE_ID) ON UPDATE CASCADE ON DELETE CASCADE PRIMARY KEY
);

CREATE TABLE DEVIL( 
DEVIL_ID SMALLSERIAL PRIMARY KEY,
LOCALE_ID SMALLINT NOT NULL DEFAULT 3 REFERENCES LOCATION(LOCALE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
PREV_MAGE INTEGER REFERENCES MAGE(MAGE_ID) ON UPDATE CASCADE,
NAME VARCHAR(25) NOT NULL UNIQUE
);

CREATE TABLE TEST( 
MAGE_ID INTEGER REFERENCES MAGE(MAGE_ID) PRIMARY KEY,
DEVIL_ID SMALLINT REFERENCES DEVIL(DEVIL_ID),
RESULT BOOLEAN DEFAULT false
);

CREATE TABLE HUMAN( 
PERSON_ID SERIAL PRIMARY KEY,
LOCALE_ID SMALLINT NOT NULL REFERENCES LOCATION(LOCALE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
EFFECT_FROM INTEGER REFERENCES MAGE(MAGE_ID) ON UPDATE CASCADE,
NAME VARCHAR(25) NOT NULL UNIQUE,
EFFECT text,
ALIVE BOOLEAN DEFAULT true
);

CREATE TABLE TRAINING( 
TRAIN_ID SERIAL PRIMARY KEY, 
LEAD_MAGE INTEGER NOT NULL REFERENCES MAGE(MAGE_ID) ON UPDATE CASCADE ON DELETE CASCADE,
SIDEKICK INTEGER REFERENCES MAGE(MAGE_ID) ON UPDATE CASCADE ON DELETE CASCADE,
VICTIM INTEGER REFERENCES HUMAN(PERSON_ID) ON UPDATE CASCADE ON DELETE CASCADE,
RESULT TEXT
);
